name: simba
description: "Liontrade Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  fl_chart: ^0.69.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-Bold.ttf
        - asset: assets/font/Manrope-ExtraBold.ttf
        - asset: assets/font/Manrope-ExtraLight.ttf
        - asset: assets/font/Manrope-Light.ttf
        - asset: assets/font/Manrope-Medium.ttf
        - asset: assets/font/Manrope-Regular.ttf
        - asset: assets/font/Manrope-SemiBold.ttf
  assets:
    - assets/images/casino.jpg
    - assets/images/bus.jpg
    - assets/images/capitol.jpg
    - assets/images/crypto.jpg
    - assets/images/gps.jpg
